name: r2b-test
services:
  read2burn:
    image: 52north/read2burn:latest
    restart: unless-stopped
    ports:
      - 3300:3300
#    volumes:
#      - ./data:/app/data
#    environment:
#      - REL_PATH=/r2b
