name: docker build publish read2burn
concurrency:
  group: "read2burn"
  cancel-in-progress: true

env:
  BUILD_CONTEXT: .
  IMAGE_AUTHORS: Jürrens, Eike Hinderk <e.h.juerrens@52north.org>
  IMAGE_DESCRIPTION: transport passwords more secure by email
  IMAGE_LICENSES: Apache-2.0
  IMAGE_TAG: 52north/read2burn
  IMAGE_TITLE: read2burn by wemove forked by 52n
  IMAGE_VENDOR: 52°North Spatial Information Research GmbH
  IMAGE_URL: https://github.com/52north/read2burn
  METADATA_TAG_PATTERN: v(.*)

on:
  workflow_dispatch:
    inputs:
      tags:
        description: "Please provide a git tag value, e.g. v1.0b3. It should be the same version as the read2burn app with added build id."
        required: true
        type: string
        default: "v1.0b3"
  push:
    tags:
      - "v*"

jobs:
  build_and_publish:
    name: docker build publish image
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: [ 'javascript' ]
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@v6
    -
      name: Declare variables and resolve Tag
      id: vars
      shell: bash
      run: |
        # Resolve Tag depending on trigger type
        if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
          CURRENT_TAG="${{ inputs.tags }}"
        else
          CURRENT_TAG="${{ github.ref_name }}"
        fi
        echo "build_date=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_OUTPUT
        echo "build_id=$(echo $CURRENT_TAG | awk -F 'b' '{print $(NF)}')" >> $GITHUB_OUTPUT
        echo "target_tag=$CURRENT_TAG" >> $GITHUB_OUTPUT
    -
      name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: ${{ matrix.language }}
    -
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:${{matrix.language}}"
    -
      name: Set up Docker Buildkit env
      uses: docker/setup-buildx-action@v4
    -
      name: Extract metadata (tags, labels) for tagging Docker Image
      id: meta
      uses: docker/metadata-action@v6
      with:
        images: "${{ env.IMAGE_TAG }}"
        labels: |
          "org.opencontainers.image.authors=${{ env.IMAGE_AUTHORS }}"
          "org.opencontainers.image.description=${{ env.IMAGE_DESCRIPTION }}"
          "org.opencontainers.image.licenses=${{ env.IMAGE_LICENSES }}"
          "org.opencontainers.image.title=${{ env.IMAGE_TITLE }}"
          "org.opencontainers.image.url=${{ env.IMAGE_URL }}"
          "org.opencontainers.image.vendor=${{ env.IMAGE_VENDOR }}"
        tags: |
          type=match,pattern=${{ env.METADATA_TAG_PATTERN }},group=1,value=${{ steps.vars.outputs.target_tag }}
    -
      name: Build Docker image (local for scanning)
      uses: docker/build-push-action@v7
      with:
        context: "${{ env.BUILD_CONTEXT }}"
        load: true
        push: false
        tags: ${{ env.IMAGE_TAG }}:local-scan
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_ID=${{ steps.vars.outputs.build_id }}
    -
      name: Run trivy vulnerability scanner
      # get latest version from https://github.com/aquasecurity/trivy-action/releases
      uses: aquasecurity/trivy-action@v0.36.0
      env:
        TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
        TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        TRIVY_DISABLE_VEX_NOTICE: "true"
      with:
        scan-type: image
        image-ref: '${{ env.IMAGE_TAG }}:local-scan'
        format: json
        output: trivy-results.json
        exit-code: '0'
        ignore-unfixed: true
        vuln-type: os,library
        scanners: vuln,secret,misconfig
        severity: CRITICAL,HIGH
    -
      name: remove empty results
      run: |
        vulnerabilities=$(cat trivy-results.json | jq 'if (.Results | length) == 0 then 0 else [.Results[].Vulnerabilities | length] | add end'); \
        if [[ "$vulnerabilities" -eq 0 ]]; then \
          rm trivy-results.json
        fi
    -
      if: ${{ hashFiles('trivy-results.json') != '' }}
      name: Convert JSON to human readable table
      # get latest version from https://github.com/aquasecurity/trivy-action/releases
      uses: aquasecurity/trivy-action@v0.36.0
      env:
        TRIVY_FORMAT: table
        TRIVY_DISABLE_VEX_NOTICE: "true"
      with:
        scan-type: convert
        scan-ref: trivy-results.json
        format: table
        output: trivy-results.txt
    -
      if: ${{ hashFiles('trivy-results.txt') != '' }}
      name: Send Trivy Results to Google Chat
      env:
        WEBHOOK_URL: ${{ secrets.GOOGLE_CHAT_WEBHOOK_URL }}
        REPO_NAME: ${{ github.repository }}
        RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      run: |
        CONTENT=$(head -n 35 trivy-results.txt)
        JSON_PAYLOAD=$(jq -n \
          --arg repo "$REPO_NAME" \
          --arg content "$CONTENT" \
          --arg url "$RUN_URL" \
          '{text: "Trivy Vulnerability Scan Failed for \($repo) \n\n```\n\($content)\n```\n\n*(Results truncated. Please review full report at \($url) )*"}')
        curl -X POST -H 'Content-Type: application/json' "$WEBHOOK_URL" -d "$JSON_PAYLOAD"
    -
      if: ${{ hashFiles('trivy-results.txt') != '' }}
      name: Halt Pipeline due to Vulnerabilities
      run: |
        echo "CRITICAL or HIGH vulnerabilities found!"
        echo "Google Chat notification sent. Halting the pipeline to prevent unsafe image push."
        exit 1
    -
      name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    -
      name: Push Docker image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v7
      with:
        context: "${{ env.BUILD_CONTEXT }}"
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        build-args: |
          GIT_COMMIT=${{ github.sha }}
          BUILD_DATE=${{ steps.vars.outputs.build_date }}
          BUILD_ID=${{ steps.vars.outputs.build_id }}
    -
      name: Trigger redeployment
      uses: actions/github-script@v9
      with:
        github-token: ${{ secrets.GHA_WORKFLOW_TRIGGER }}
        script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: '${{ secrets.TRIGGER_ORGA }}',
              repo: '${{ secrets.TRIGGER_REPO }}',
              workflow_id: '${{ secrets.TRIGGER_WORKFLOW_1 }}',
              ref: '${{ secrets.TRIGGER_REF }}'
            })
            console.log(result)
